apiVersion: v1
kind: Service
metadata:
  name: website-service # Name of the service
spec:
  type: LoadBalancer 
  ports:
    - port: 80 # Port on which the service (Load Balancer) is listening
      targetPort: 80 # Port on which the POD is running
  selector:
    app: web-app # Pods with this label will be targeted
